# Welcome to Jekyll!

#port: 1001
title: Awesome Site
description: Jekyll x Bootstrap@5.2 Boilerplate.
baseurl: "/jekyll-boilerplate" 
localurl: "<%= ENV['LOCAL_URL'] %>"
url: ""
lang: "id"

# Markdown settings
markdown: kramdown

# Sass settings
sass:
  add_charset: true
  sass_dir: assets/sass
  style: :compressed

# Build settings
exclude:
  - package.json
  - README.md
  - CNAME
  - assets/sass

# Plugin settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - dotenv
  - jekyll-minify-html

plugins_dir: _plugins

collections:
  blog:
    output: true
  admin:
    output: true
  product:
    output: true
chat-ai:
    output: true

# Firebase
api_key: "<%= ENV['api_key'] %>"
auth_domain: "<%= ENV['auth_domain'] %>"
project_id: "<%= ENV['project_id'] %>"
database_url: "<%= ENV['database_url'] %>"
storage_bucket: "<%= ENV['storage_bucket'] %>"
sender_id: "<%= ENV['sender_id'] %>"
app_id: "<%= ENV['app_id'] %>"
measure_id: "<%= ENV['measure_id'] %>"


compress_html:
  clippings: all
  ignore:
    envs: development
